### PR TITLE
fixed empty page handling on pageToItem conversion

### PR DESCRIPTION
**Pull request by ckolumbus**

### CODE REVIEW

**Comment by ShadowKyogre** [comment]
Patch lookgs good. Before I merge it, I just wanna know what places in code end up calling pageToTiem with an empty string. (<- since this might be helpful for pointing out other problems)

**Comment by ckolumbus** [comment]
I found the problem when investigating the "file://" versus "file:///" handing under windows. The internal links got messed up when working under windows and finally the pageToItem function got called with an empty string. So 'page[0]' threw an exception.
Frankly, I'm not sure whether this should happen at all if the code fixes that I'm working on are properly done, BUT thinking of defensive programming the check above might still make sense. 

You might want to check out my development branch [develop-ckol-fileurlhandling](https://github.com/ckolumbus/mikidown/tree/develop-ckol-fileurlhandling) regarding the current work. Still needs to be tested under windows AND linux :-)

**Comment by ShadowKyogre** [comment]
@ckolumbus : Understood! I'll merge this and check out the development branch you linked me. Thanks bunches for checking that (esp. since I usually do most of my work on my Linux compy).

**Comment by ckolumbus** [comment]
I also do all my stuff with Linux BUT at work we are quite windows-centric. Python is a great environment for cross-platform tooling, that's why I also like Mikidown.  I'm phasing lot's of my docs over to markdown. Sofar I use [WikidPad](https://github.com/butscher/WikidPad) and it's great BUT has it's own markup language, bummer. Therefore I'm so interested in Mikidown to have a cross-platform doc utility based on markdown :-)
My dev branch mentioned is far from beeing ready, but if you have a look you might be able to give early feedback.

**Pull request merged**
