### PR TITLE
qt5 WIP

### PR DESCRIPTION
**Pull request by pedromorgan**
Started some porting to Qt5, comments appreciated

### CODE REVIEW

**Comment by ShadowKyogre** [comment]
Thumbing through this and fixing the conflicts/missed spots along the way (they're minor). Out of curiosity, were the API docs added so that people have an easier time browsing through the code?

**Comment by pedromorgan** [comment]
Yep, so I can get an idea of whats going on.. and then figuring it out,, ;-))

You done a lot of hard work .. and thanks for that..

**Comment by pedromorgan** [comment]
BTW There are still some NON qt5 code.. haven found then all yet... aplologies..

**Comment by ShadowKyogre** [comment]
@pedromorgan: Thanks! I know there's still some non-Qt5 code. Caught one of those instances as I was thumbing through the merge. I'll poke the UI some more to make sure I haven't missed anything regarding that.

Also, could you link me to a tutorial on how to add sphinx docs like the ones you put in here for python projects? It's something I've been meaning to do for all my other projects, but it kept going over my head.

**Comment by ShadowKyogre** [comment]
Merged the WIP so far. Prodding mikiedit.py some more to clean up the missing prefixes.

**Comment by pedromorgan** [comment]
Re non-qt5.. cool stuff...
maybe merge into develop5/
Can us add me as project commiter to that branch ?

Re the Tutorial on shpinx, then I'm afraid its a "dark art", and one of the dilemas
is that with Qt, the only way to do it is to gen docs local, and upload..
There's just so many quirks with sphinx, and i hate it, hate it hate it..
even more than @javadoc etc, as it tries to be the jack of all trades
and a master of none..
Golanf aand godoc is cool, and clean, but even then i want some "md" in content
is my opinion, at 53 years olde next month...

http://docs-ts2.rhcloud.com/

**Comment by ShadowKyogre** [comment]
@pedromorgan: Sure thing! Gimme just one moment.

And wow o_o; I'm glad I'm not the only one that thought that sphinx was pretty arcane too.

**Pull request merged**
